### ISSUE TITLE
Getting time in ms format

### ISSUE THREAD

**Issue by ohad-griiip** [semuconsulting/pyubx2#13]
Something I trying to accomplish for some time now is to be able to get timestamp with ms precision, as for when I send a NAV-PVT message the response is up to seconds. I do get the nano field but oddly this is a 6 digit number so it doesn't contain any milliseconds info... I've tried to configure the time pulse thinking maybe it'll change the resolution but am yet to have it working for this.

I'm asking the question here just thought maybe I could get help here, since I've been going through the datasheet lately but I feel like I'm missing something 🤔.

Help would be very appreciated!

**Comment by semuadmin** [comment]
Hi,

Not sure why it's been designed this way, but this is expected behaviour. If the navigation solution interval is a multiple of whole seconds, the nano field comes back as 6 digits, but if you set the solution interval to a fractional second value (e.g. 100ms or 200ms) you will start to see the nano field come back with 9 digits, including millisecond values (_I'm guessing the reasoning is that if you're only taking a position solution at whole seconds, you're not bothered about the milliseconds???_)

e.g. here's a NAV-PVT message with solution interval set to 1000ms (i.e. 1 Hz, the default with most standard devices):

<UBX(NAV-PVT, iTOW=12:30:34, year=2021, month=3, day=11, hour=12, min=30, second=32, valid=b'7', tAcc=27, nano=**365524**, fixType=3, flags=b'\x01', flags2=b'\xea', numSV=17, lon=-21232382, lat=512307334, height=90061, hMSL=41577, hAcc=3703, vAcc=3321, velN=69, velE=14, velD=43, gSpeed=71, headMot=35236592, sAcc=875, headAcc=4125051, pDOP=130, reserved1=52016683286528, headVeh=0, magDec=0, magAcc=0)>

... and here's a NAV-PVT message with the solution interval set to 100ms (i.e. 10Hz):

<UBX(NAV-PVT, iTOW=12:26:21.500000, year=2021, month=3, day=11, hour=12, min=26, second=19, valid=b'7', tAcc=25, nano=**500349559**, fixType=3, flags=b'\x01', flags2=b'\xea', numSV=12, lon=-21232208, lat=512306896, height=85667, hMSL=37183, hAcc=2376, vAcc=2172, velN=-10, velE=82, velD=1, gSpeed=83, headMot=14830342, sAcc=354, headAcc=6644024, pDOP=168, reserved1=52016683286528, headVeh=0, magDec=0, magAcc=0)>

If you want to change the solution interval to check this out, you can either send a CFG-RATE message or a CFG-VALSET message with a keyid of 0x30210001 ("CFG_RATE_MEAS").

Hope this helps.
